dashboard/urls.py
from django.urls import path
from . import views

from .views import GeneratePdf


urlpatterns = [
    # Activities
    path('admin/', views.admin, name='adminPage'),
    path('access-award/', views.access_award_by_code, name='access_award_by_code'),
    path('activity-category/<slug:category_slug>/', views.activity_category, name='activity_category'),
    path('activity-nominee/<slug:nominee_slug>/', views.activity_nominee, name='activity_nominee'),
    
    path('vote-in-order-by-category/<slug:category_slug>/', views.vote_in_order_by_category, name='vote_in_order_by_category'),
    
    # Registration
    path('registration/', views.registration, name='registration'),
    path('registration-category/', views.registration_category, name='registration_category'),
    path('registration-nominee/<slug:register_slug>/', views.registration_nominee, name='registration_nominee'),
    
    # Transaction
    path('transaction/<slug:nominee_slug>/', views.transaction, name='transaction'),

    path('transaction-category/<slug:transaction_slug>/', views.transaction_category, name='transaction_category'),

    path('team/', views.team, name='team'),

    path('transaction-category/<slug:transaction_slug>/', views.transaction_category, name='transaction_category'),
    path('adminHome/', views.adminHome, name='adminHome'),
    path('TransactionMain/', views.TransactionMain, name='TransactionMain'),
    path('access-award-transactions/', views.access_transaction_by_code, name='access_transaction_by_code'),
    path('ussd_transactions/<int:category_id>/', views.ussd_transactions, name='ussd_transactions'),
    path('online_transactions/<int:category_id>/', views.online_transactions, name='online_transactions'),
    path('TransactionCat/<slug:category_slug>/', views.TransactionCat, name='TransactionCat'),

    # PDF
    path('generate/<pdf>/', views.generate, name='generate'),
    path('pdf/<form>/', GeneratePdf.as_view(), name='pdf'),
    
    
    # path('add_nominee/', views.add_nominee, name='add_nominee'),
    # path('get_subcategories/', GetSubCategoriesView.as_view(), name='get_subcategories'),
    # path('sms/', views.send_sms, name='send_sms'),
    # path('send-category-sms/', views.send_sms_to_nominees, name='send_category_sms'),
    # path('send-access-code/', views.send_access_code_to_nominee, name='send_access_code'),
    # path('award_revenue_insight/<int:subcategory_id>/', views.award_revenue_insight, name='award_revenue_insight'),
    
    # path('get_all_categories/', views.get_all_categories, name='get_all_categories'),
    # path('get_all_nominees/<slug:category_slug>/', views.get_nominee_by_category, name='get_nominee_by_category'),
    # path('update_nominee/<slug:nominee_slug>/', views.update_nominee_by_category, name='update_nominee'),
    
    # path('payment-transactions/', views.payment_transactions, name='payment_transactions'),
    # path('payment-transactions/<int:invoice_id>/', views.payment_transactions_detail, name='update_transaction'),
    


     path('accessTicket/', views.accessTicket, name='accessTicket'),
     path('ticketActivity/<slug:event_slug>/', views.ticketActivity, name='ticketActivity'),
     path('onlineTransaction/<int:event_id>/', views.onlineTransaction, name='onlineTransaction'),
     path('ussdTransaction/<int:event_id>/', views.ussdTransaction, name='ussdTransaction'),
    
     path('request-payment/<slug:category_slug>/', views.request_for_payment, name='request_payment'),
]

maindashboard/urls.py
from django.urls import path
from . import views
from .views import GetSubCategoriesView

urlpatterns = [
    path('admin/', views.dashboard, name='main_dashboard'),
    path('add_nominee/', views.add_nominee, name='add_nominee'),
    path('get_subcategories/', GetSubCategoriesView.as_view(), name='get_subcategories'),
    path('sms/', views.send_sms, name='send_sms'),
    path('send-category-sms/', views.send_sms_to_nominees, name='send_category_sms'),
    path('send-access-code/', views.send_access_code_to_nominee, name='send_access_code'),
    
    path('get_all_categories/', views.get_all_categories, name='get_all_categories'),
    path('get_all_nominees/<slug:category_slug>/', views.get_nominee_by_category, name='get_nominee_by_category'),
    path('update_nominee/<slug:nominee_slug>/', views.update_nominee_by_category, name='update_nominee'),
    
    path('bulk_voting_transactions/<slug:category_slug>/', views.get_bulk_voting_transactions_by_category, name='bulk_voting_transactions'),
    
    path('payment-transactions/', views.payment_transactions, name='payment_transactions'),
    path('payment-transactions/<int:invoice_id>/', views.payment_transactions_detail, name='update_transaction'),
    
    path('filter_online_transactions/', views.filter_online_transactions, name='filter_online_transactions'),
    
    path('blog_list/', views.blog_list, name='blog_list'),
    path('add_blog/', views.add_blog, name='add_blog'),
    path('update_blog/<int:blog_id>/', views.update_blog, name='update_blog'),
    path('delete_blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),

    path('receipt/', views.receipt, name='receipt'),
]

user/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

votehere/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
from vote.sitemaps import *
from django.views.generic.base import TemplateView

# Sitemaps
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticSitemap,
    'categories': CategorySitemap,
    'subcategorypages': SubcategorySitemap
}

urlpatterns = [
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt/', TemplateView.as_view(template_name="vote/robots.txt", content_type="text/plain")),
    path('voteafric_admin/', admin.site.urls),
    path('', include('vote.urls')),
    path('voting/', include('voting.urls')),
    path('payment/', include('payment.urls')),
    path('register/', include('register.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('maindashboard/', include('maindashboard.urls')),
    path('user/', include('user.urls')),
    path('ussd/', include('ussd.urls')),
    path('/', include('ticket.urls')),
    path('donation/', include('donation.urls')),
    path('api/vote/', include('vote.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'vote.views.custom_404_view'

dashboard/models.py
from django.db import models

# Create your models here.
class SendSms(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=10, default='')
    category = models.CharField(max_length=100)
    date_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

maindashboard/models.py
from django.db import models

dashboard/views.py
from decimal import Decimal
from django.shortcuts import render, get_object_or_404, redirect
from vote.models import Category, SubCategory
from payment.models import Nominees, Payment, RequestForPayment
from register.models import Register
from django.db.models import Sum
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from django.http import HttpResponse
from django.views.generic import View
from .utils import render_to_pdf, send_sms_to_new_nominee, send_mnotify_sms, send_access_code_to_new_nominee, request_for_payment_sms, receive_request_for_payment_sms
from payment.forms import NomineeForm
from django.contrib import messages
from .forms import RequestForPaymentForm, SendSmsForm, NomineeForm, CategorySMSForm, PaymentTransactionForm, AccessCodeSMSForm
from ussd.models import PaymentTransaction

from ticket.models import Event, TicketPayment

from django.http import JsonResponse
from django.views import View

# Create your views here.

def access_award_by_code(request):
    if request.method == 'POST':
        code = request.POST.get('access_code')
        try:
            award = Category.objects.get(access_code=code)
            return redirect('activity_category', award.slug)
        except Category.DoesNotExist:
            messages.error(request, "Invalid access code. Please try again.")
            return redirect('access_award_by_code')  # or wherever your admin view is named
    
    return render(request, 'dashboard/access_code_form.html')

def admin(request):
    awards = Category.objects.all()
    context = {
        'awards': awards,
        'title': 'adminPage'
    }
    return render(request, 'dashboard/admin.html', context)

def activity_category(request, category_slug):
    category = None
    award = SubCategory.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        award = award.filter(category=category)

    context = {
        'category': category,
        'award': award,
        'title': 'adminPage'
    }
    
    return render(request, 'dashboard/activity-category.html', context)

def activity_nominee(request, nominee_slug):
    sub_category = None
    nominees = Nominees.objects.all()
    if nominee_slug:
        sub_category = get_object_or_404(SubCategory, slug=nominee_slug)
        nominees = nominees.filter(sub_category=sub_category)
        total_votes = nominees.aggregate(total=Sum('total_vote'))
        total_votes = total_votes['total']

        

    context = {
        'sub_category': sub_category,
        'nominees': nominees,
        'total_votes': total_votes,
        'title': 'adminPage'
    }

    return render(request, 'dashboard/activity-nominee.html', context)

def registration(request):
    awards = Category.objects.all()
    context = {
        'awards': awards,
        'title': 'adminPage'
    }

    return render(request, 'dashboard/registration.html', context)


def registration_category(request):
    
    context = {
        'title': 'adminPage'
    }
    return render(request, 'dashboard/registration-category.html', context)



def registration_nominee(request, register_slug):
    award = None
    registers = Register.objects.all()
    if register_slug:
        award = get_object_or_404(Category, slug=register_slug)
        registers = registers.filter(award=award)
        register_count = registers.filter(award=award).count()

    context = {
        'award': award,
        'registers': registers,
        'register_count': register_count,
        'title': 'adminPage'
    }

    return render(request, 'dashboard/registration-nominee.html', context)



def transaction(request, nominee_slug):
    sub_category = None
    nominees = Nominees.objects.all()
    if nominee_slug:
        sub_category = get_object_or_404(SubCategory, slug=nominee_slug)
        nominees = nominees.filter(sub_category=sub_category)
        
        total_votes = nominees.aggregate(total=Sum('total_vote'))
        total_votes = total_votes['total']

    context = {
        'sub_category': sub_category,
        'nominees': nominees,
        'total_votes': total_votes,
        'title': 'adminPage'
    }

    return render(request, 'dashboard/transaction.html', context)

def team(request):
   
    context = {
      
        'title': 'team'
    }
    return render(request, 'dashboard/team.html', context)

@login_required(login_url='login')
def adminHome(request):
    awards = Category.objects.all()
    award_count = Category.objects.all().count()
    category_count = SubCategory.objects.all().count()
    nominee_count = Nominees.objects.all().count()
    current_time = timezone.now()
    context = {
        'awards': awards,
        'current_time': current_time,
        'award_count': award_count,
        'category_count': category_count,
        'nominee_count': nominee_count,
        'title': 'adminHome'
    }
    return render(request, 'dashboard/adminHome.html', context)


def access_transaction_by_code(request):
    if request.method == 'POST':
        code = request.POST.get('access_code')
        try:
            award = Category.objects.get(access_code=code)
            return redirect('TransactionCat', award.slug)
        except Category.DoesNotExist:
            messages.error(request, "Invalid access code. Please try again.")
            return redirect('access_transaction_by_code')  # or wherever your admin view is named
    
    return render(request, 'dashboard/access_transaction_code_form.html')

def TransactionMain(request):
    awards = Category.objects.all()
    context = {
        'awards': awards,
        'title': 'TransactionMain'
    }
    return render(request, 'dashboard/transactionMain.html', context)


def TransactionCat(request, category_slug):
    category = None 
    award = SubCategory.objects.all()
    online_payments = Payment.objects.all()
    ussd_payments = PaymentTransaction.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        award = award.filter(category=category)
        online_payments = online_payments.filter(category=category, verified=True)
        ussd_payments = ussd_payments.filter(category=category, status='PAID')
        
        # Calculate online payments total and deduct 2%
        total_online = online_payments.aggregate(Total=Sum('total_amount')).get('Total', 0) or 0
        total_online_payments = Decimal(total_online) * Decimal(0.98)  # Deduct 2%
        
       
        
        
        # Calculate USSD payments total and deduct 3%
        total_ussd = ussd_payments.aggregate(Total=Sum('amount')).get('Total', 0) or 0
        total_ussd_payments = total_ussd * Decimal(0.97)  # Deduct 3%
        # total_ussd_payments = total_ussd_value.quantize(Decimal('1'))
        
        # Optionally keep original totals if needed
        original_online_total = Decimal(total_online)
        original_ussd_total = Decimal(total_ussd)
        
        # Calculate sum of original totals
        sum_total = original_online_total + original_ussd_total
        
        original_total_payment = sum_total * Decimal(0.97)  # Deduct 5% from the total sum

    context = {
        'category': category,
        'award': award,
        'total_online_payments': total_online_payments,
        'total_ussd_payments': total_ussd_payments,
        'original_online_total': original_online_total,
        'original_ussd_total': original_ussd_total,
        'original_total_payment': original_total_payment,
        'sum_total': sum_total,
        'title': 'TransactionCat'
    }

    return render(request, 'dashboard/transactionCat.html', context)

def vote_in_order_by_category(request, category_slug):
    category = None
    award = SubCategory.objects.all()
    nominees = Nominees.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        award = award.filter(category=category)
        nominees = nominees.filter(category=category).order_by('-total_vote')
        total_votes = nominees.aggregate(total=Sum('total_vote'))
        total_nominees = nominees.count()

    context = {
        'category': category,
        'award': award,
        'nominees': nominees,
        'total_votes': total_votes['total'] if total_votes['total'] else 0,
        'nominee_count': total_nominees,
        'title': 'Vote in order by category'
    }
    
    return render(request, 'dashboard/vote_in_order_by_category.html', context)

def transaction_category(request, transaction_slug):
    nominee = None
    payments = Payment.objects.all()
    if transaction_slug:
        nominee = get_object_or_404(Nominees, slug=transaction_slug)
        all_payments = payments.filter(nominee=nominee)
        verified_payments = payments.filter(nominee=nominee, verified=True)
        not_verified_payments = payments.filter(nominee=nominee, verified=False)
        total_amount_verified = verified_payments.aggregate(Total=Sum('total_amount'))
        total_amount_not_verified = not_verified_payments.aggregate(Total=Sum('total_amount'))
        total_amount = all_payments.aggregate(Total=Sum('total_amount'))
        total_amount_verified = total_amount_verified['Total']
        total_amount_not_verified = total_amount_not_verified['Total']
        total_amount = total_amount['Total']

    context = {
        'nominee': nominee,
        'all_payments': all_payments,
        'verified_payments': verified_payments,
        'not_verified_payments': not_verified_payments,
        'total_amount_verified': total_amount_verified,
        'total_amount_not_verified': total_amount_not_verified,
        'total_amount': total_amount,
        'title': 'adminPage'
    }
    return render(request, 'dashboard/transaction-category.html', context)


def ussd_transactions(request, category_id):
    category = None
    payments = PaymentTransaction.objects.all()
    
    # Get filter parameters from request GET

maindashboard/templates/maindashboard/add_blog.html
{% extends 'maindashboard/base.html' %}
{% load static %}
{% block content %}
<style>
    /* General form styling */
    .add-nominee-form {
        max-width: 400px;
        margin: 20px auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    /* Style for form elements */
    .add-nominee-form p {
        margin-bottom: 15px;
    }

    .add-nominee-form label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .add-nominee-form input,
    .add-nominee-form select,
    .add-nominee-form textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
        box-sizing: border-box;
    }

    /* Button styling */
    .add-nominee-form button {
        display: block;
        width: 100%;
        padding: 10px;
        background: #007bff;
        color: white;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background 0.3s ease;
    }

    .add-nominee-form button:hover {
        background: #0056b3;
    }
</style>
<div class="main">
    <div class="the-team-container">
        <div class="heading">
            <h1>Add Blog</h1>
        </div>

    </div>
    <div style="background-color:#000; width:100%;">
        {% if messages %}
        {% for message in messages %}
        <p style="color: #97c8b3; font-size:30px; text-align:center;">{{ message }}</p>
        {% endfor %}
        {% endif %}
    </div>


    <form class="add-nominee-form" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <!-- {{form.category.label_tag}}
            {{form.category}}
            {{form.sub_category.label_tag}}
            {{form.sub_category}}
            {{form.name.label_tag}}
            {{form.name}}
            {{form.image.label_tag}}
            {{form.image}}
            {{form.slug.label_tag}}
            {{form.slug}}
            {{form.code.label_tag}}
            {{form.code}}
            {{form.access_code.label_tag}}
            {{form.access_code}}
            {{form.phone_number.label_tag}}
            {{form.phone_number}}
            {{form.date_added.label_tag}}
            {{form.date_added}}
            {{form.end_date.label_tag}}
            {{form.end_date}} -->


        <button type="submit">Save</button>

    </form>


</div>

<div class="logout-pop">
    <div class="logout">
        <p>Are you sure you want to log out from the admin pannel ?</p>
        <div class="log-button">
            <a href="{% url 'logout' %}">
                <button>Log Out</button>
            </a>

            <p>Or</p>

            <button class="DontLogout">No</button>
        </div>
    </div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_category').change(function () {
            var categoryId = $(this).val();
            if (categoryId) {
                $.ajax({
                    url: '/maindashboard/get_subcategories/',
                    data: {
                        'category_id': categoryId
                    },
                    success: function (data) {
                        $('#id_sub_category').html(data);
                    }
                });
            } else {
                $('#id_sub_category').html('<option value="">---------</option>');
            }
        });
    });
</script>
{% endblock %}

maindashboard/templates/maindashboard/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, 
				initial-scale=1.0">
    <link rel="icon" href="{% static 'vote/img/our-logo.jpg' %}" type="image/jpeg">
    <title>Admin Page</title>
    <link rel="stylesheet" href="{% static 'vote/admin.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <!-- for header part -->
    <header>

        <div class="logosec">
            <div class="logo">
                <a href="{% url 'index' %}"><img src="{% static 'vote/img/voteafric-logo.png' %}" alt="geima"></a>
            </div>
            <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210182541/Untitled-design-(30).png"
                class="icn menuicn" id="menuicn" alt="menu-icon">
        </div>



        <div class="message">
            <h1>Admin Dashboard</h1>
        </div>

    </header>

    <div class="main-container">
        <div class="navcontainer sidebar">
            <nav class="nav">
                <div class="nav-upper-options">

                    <!-- home button -->
                    <a href="{% url 'main_dashboard' %}">

                        <div class="nav-option option1 button">
                            <h3><i class="fa-solid fa-house"></i> Home</h3>
                        </div>
                    </a>
                    <!-- acivities button -->
                    <!-- <a href="{% url 'access_award_by_code' %}">

                        <div class="nav-option option1 button">
                            <h3><i class="fa-solid fa-chart-simple"></i> Activities</h3>
                        </div>
                    </a> -->
                   <a href="{% url 'receipt' %}">

                        <div class="nav-option option1 button">
                            <h3><i class="fa-solid fa-chart-simple"></i> Receipt</h3>
                        </div>
                    </a>


                    <!-- registration button -->
                    <!-- <a href="{% url 'registration' %}">
    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> Nominations</h3>
                        </div>
                    </a> -->


                    <!-- registration button -->
                    <!-- <a href="{% url 'access_transaction_by_code' %}">
                        <div class="nav-option option1 button">
                            <h3> <i class="fa-solid fa-money-bill"></i> Transactions</h3>
                        </div>
                    </a> -->
                    <!-- <a href="{% url 'accessTicket' %}">
                        <div class="nav-option option1 button">
                            <h3> <i class="fa-solid fa-money-bill"></i> Events</h3>
                        </div>
                    </a> -->
                    <a href="{% url 'send_sms' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> New Nominee SMS</h3>
                        </div>
                    </a>
                    <a href="{% url 'send_category_sms' %}">
                        <div class="nav-option option1 button">
                            <h3> <i class="fa-solid fa-money-bill"></i> SMS to Nominees</h3>
                        </div>
                    </a>
                    <a href="{% url 'send_access_code' %}">
                        <div class="nav-option option1 button">
                            <h3> <i class="fa-solid fa-money-bill"></i> Send Access Code</h3>
                        </div>
                    </a>
                    <a href="{% url 'add_nominee' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> Add Nominee</h3>
                        </div>
                    </a>
                    
                    <a href="{% url 'get_all_categories' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> All Categories</h3>
                        </div>
                    </a>
                    <a href="{% url 'blog_list' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> Blogs</h3>
                        </div>
                    </a>
                    <a href="{% url 'payment_transactions' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> USSD Transactions</h3>
                        </div>
                    </a>
                    <a href="{% url 'filter_online_transactions' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> Online Transactions</h3>
                        </div>
                    </a>
                    <a href="{% url 'search_transaction' %}">
                    
                        <div class="nav-option option1 button ">
                            <h3> <i class="fa-solid fa-cash-register"></i> Verify Transaction</h3>
                        </div>
                    </a>


                    <!-- team button -->
                    <!-- <a href="{% url 'team' %}">
                        <div class="nav-option option1 button">
                            <h3><i class="fa-solid fa-people-group"></i> Team</h3>
                        </div>
                    </a> -->

                    <div class="nav-option option1 button Settings">
                        <div class="sett-but">
                            <h3><i class="fa-solid fa-sliders"></i> Settings </h3>
                            <i class="fa-solid fa-caret-down"></i>
                        </div>

                        <button class="darkMode-button">Change background Mode</button>
                    </div>

                    <!-- logout button -->

                    <div class="nav-option option1 button logout-btn">
                        <h3>Logout</h3>
                    </div>

                    




                </div>
            </nav>
        </div>


        {% block content %}{% endblock %}
        <script defer src="{% static 'vote/adminScript.js' %}"></script>
        <script defer src="{% static 'vote/adminScript2.js' %}"></script>


</body>

</html>

maindashboard/templates/maindashboard/update_blog.html
{% extends 'maindashboard/base.html' %}
{% load static %}
{% block content %}
<style>
    /* General form styling */
    .add-nominee-form {
        max-width: 400px;
        margin: 20px auto;
        padding: 20px;
        background: #f9f9f9;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    /* Style for form elements */
    .add-nominee-form p {
        margin-bottom: 15px;
    }

    .add-nominee-form label {
        font-weight: bold;
        display: block;
        margin-bottom: 5px;
    }

    .add-nominee-form input,
    .add-nominee-form select,
    .add-nominee-form textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 16px;
        box-sizing: border-box;
    }

    /* Button styling */
    .add-nominee-form button {
        display: block;
        width: 100%;
        padding: 10px;
        background: #007bff;
        color: white;
        border: none;
        border-radius: 5px;
        font-size: 16px;
        cursor: pointer;
        transition: background 0.3s ease;
    }

    .add-nominee-form button:hover {
        background: #0056b3;
    }
</style>
<div class="main">
    <div class="the-team-container">
        <div class="heading">
            <h1>Update Blog</h1>
        </div>

    </div>
    <div style="background-color:#000; width:100%;">
        {% if messages %}
        {% for message in messages %}
        <p style="color: #97c8b3; font-size:30px; text-align:center;">{{ message }}</p>
        {% endfor %}
        {% endif %}
    </div>


    <form class="add-nominee-form" method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <!-- {{form.category.label_tag}}
            {{form.category}}
            {{form.sub_category.label_tag}}
            {{form.sub_category}}
            {{form.name.label_tag}}
            {{form.name}}
            {{form.image.label_tag}}
            {{form.image}}
            {{form.slug.label_tag}}
            {{form.slug}}
            {{form.code.label_tag}}
            {{form.code}}
            {{form.access_code.label_tag}}
            {{form.access_code}}
            {{form.phone_number.label_tag}}
            {{form.phone_number}}
            {{form.date_added.label_tag}}
            {{form.date_added}}
            {{form.end_date.label_tag}}
            {{form.end_date}} -->


        <button type="submit">Save</button>

    </form>


</div>

<div class="logout-pop">
    <div class="logout">
        <p>Are you sure you want to log out from the admin pannel ?</p>
        <div class="log-button">
            <a href="{% url 'logout' %}">
                <button>Log Out</button>
            </a>

            <p>Or</p>

            <button class="DontLogout">No</button>
        </div>
    </div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('#id_category').change(function () {
            var categoryId = $(this).val();
            if (categoryId) {
                $.ajax({
                    url: '/maindashboard/get_subcategories/',
                    data: {
                        'category_id': categoryId
                    },
                    success: function (data) {
                        $('#id_sub_category').html(data);
                    }
                });
            } else {
                $('#id_sub_category').html('<option value="">---------</option>');
            }
        });
    });
</script>
{% endblock %}